DROP TABLE IF EXISTS movie;
CREATE TABLE movie(
   Title              VARCHAR(35) NOT NULL PRIMARY KEY
  ,Release_Year       INTEGER  NOT NULL
  ,Fun_Facts          VARCHAR(339)
  ,Production_Company VARCHAR(39) NOT NULL
  ,Distributor        VARCHAR(42)
  ,Director           VARCHAR(79) NOT NULL
  ,Writer             VARCHAR(49) NOT NULL
  ,Actor_1            VARCHAR(21) NOT NULL
  ,Actor_2            VARCHAR(22)
  ,Actor_3            VARCHAR(18)
);
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('180',2011,NULL,'SPI Cinemas',NULL,'Jayendra','Umarji Anuradha, Jayendra, Aarthi Sriram, & Suba','Siddarth','Nithya Menon','Priya Anand');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Around the Fire',1998,'On Jan. 25, 1878, the King Philip ship crashed in Ocean Beach. Occasionally, the ship''s wreckage may be found on the beach-- most recently it was seen in 2007.','Paradigm Studio','Ardustry Home Entertainment','John Jacobsen','John Comerford','Tara Reid',NULL,NULL);
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Basic Instinct',1992,'The Steinhart Aquarium is home to over 38,000 animals, which represent more than 900 species.','Carolco Pictures','TriStar Pictures','Paul Verhoeven','Joe Eszterhas','Michael Douglas','Sharon Stone','George Dzundza');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Bedazzled',2000,'Installed in 1975, the Vaillancourt Fountain is officially titled, "Québec Libre!". The night before the sculpture''s inauguration, artist Armand Vaillancourt inscribed "Québec libre!" in red letters on the sculpture. The next day when he noticed that the note had been erased, Vaillancourt jumped on the statue to re-inscribe his message.','Twentieth Century Fox Film Corp.','Twentieth Century Fox Film Corp.','Harold Ramis','Harold Ramis','Brendan Fraser','Elizabeth Hurley',NULL);
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Dr. Dolittle 2',2001,'In 1776, Spain made the Presidio a fortified area. The area was then given to Mexico, but then given to the US in 1848. The 1994 demilitarization of the area in 1994 marked the end of its 219 years of military use.','Twentieth Century Fox Film Corp.','Twentieth Century Fox Film Corp.','Steve Carr','Larry Levin','Eddie Murphy','Kristen Wilson',NULL);
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Final Analysis',1992,'The hotel was originally supposed to be named the Crocker Hotel, after Charles Founder the railroad magnate who founded it. However, the hotel took the name the St. Francis after one of the earliest Gold Rush hotels.','Warner Bros. Pictures','Warner Bros. Pictures','Phil Joanou','Robert Berger','Richard Gere','Kim Basinger',NULL);
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('George of the Jungle',1997,'Before opening in 1936, the bridge was blessed by Cardinal Secretary of State Eugenio Pacelli, who later became Pope Pius XII.','Walt Disney Pictures','Buena Vista Pictures','Sam Weisman','Jay Ward','Brendan Fraser','Leslie Mann',NULL);
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('High Crimes',2002,'During the Civil War, pro-Union rallies were held in the Square, and thus the area was called "Union Square".','Twentieth Century Fox Film Corporation','Twentieth Century Fox Film Corporation','Mel Brooks','Mel Brooks','Mel Brooks','Madeline Kahn',NULL);
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Patch Adams',1998,'The hotel was destroyed in the 1906 earthquake and fire, had to be rebuilt, and was reopened in 1909.','Bungalow 78 Productions','Universal Pictures','Tom Shadyac','Steve Oedekerk','Robin Williams','Philip Seymour Hoffman',NULL);
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Bachelor',1999,'The Steinhart Aquarium is home to over 38,000 animals, which represent more than 900 species.','George Street Pictures','New Line Cinema','Gary Sinyor','Steve Cohen','Chris O''Donnell','Renee Zellweger',NULL);
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Candidate',1972,'The hotel was originally supposed to be named the Crocker Hotel, after Charles Founder the railroad magnate who founded it. However, the hotel took the name the St. Francis after one of the earliest Gold Rush hotels.','Redford-Ritchie Productions','Warner Bros. Pictures','Michael Ritchie','Jeremy Larner','Robert Redford','Peter Boyle',NULL);
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('When a Man Loves a Woman',1994,'The hotel was originally supposed to be named the Crocker Hotel, after Charles Founder the railroad magnate who founded it. However, the hotel took the name the St. Francis after one of the earliest Gold Rush hotels.','Touchstone Pictures','Buena Vista Pictures','Luis Mandoki','Ronald Bass','Andy Garcia','Meg Ryan',NULL);
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Pushing Dead',2016,'Pushing Dead won the Audience Award for  Frameline San Francisco International LGBTQ Film Festival 
2016','Pushing Dead , LLC','TBD','Tom Brown','Tom Brown','Danny Glover','James Roday','Robin Weigert');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('GirlBoss',2017,'The restaurant was given the honor of "America''s Best Burrito" in 2014 by ESPN''s FiveThirtyEight.','Hippolyta Productions, LLC','Netflix','Jamie Babbit, Amanda Brotchie, Steven K. Tsuchida, Christian Ditter, John Riggi','Kay Cannon','Britt Robertson','Ellie Reed','Amanda Rea');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Game',1997,'The hotel was destroyed in the 1906 earthquake and fire, had to be rebuilt, and was reopened in 1909.','Polygram Filmed Entertainment','Polygram Filmed Entertainment','David Fincher','John Brancato','Michael Douglas','Sean Penn','Deborah Kara Unger');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('D.O.A',1950,'During the Civil War, pro-Union rallies were held in the Square, and thus the area was called "Union Square".','Cardinal Pictures','United Artists','Rudolph Mate','Russell Rouse','Edmond O''Brien','Pamela Britton','Luther Adler');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Freebie and the Bean',1974,'Railroad tycoons like Leland Stanford (founder of Stanford University) lived in Nob Hill at the turn of the 20th Century. The 1906 earthquake completely destroyed Nob Hill, with the exception of the wall that surrounded the mansions of Stanford and his neighbor Mark Hopkins.','Warner Bros. Pictures','American Broadcasting Company (ABC)','Richard Rush','Robert Kaufman','Alan Arkin','James Caan','Loretta Swit');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Sense8 - Season 2',2016,'Many films have shot scene in and around the building including Raiders of the Lost Ark, Invasion of the Body Snatchers, Dirty Harry, The Towering Inferno, A View to a Kill and most recently, Milk. The Christmas party scene for this show was shot in the Rotunda.','Unpronounceable Productions, LLC','Netflix','Wachowski Siblings','J. Michael Straczynski, Wachowiski Siblings','Jamie Clayton','Daryl Hannah','Naveen Andrews');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Hard to Hold',1984,'In 1945 the Fairmont hosted the United Nations Conference on International Organization as delegates arrived to draft a charter for the organization. The U.S. Secretary of State, Edward Stettinius drafted the charter in the hotel''s Garden Room.','Universal Pictures','Universal Pictures','Larry Peerce','Thomas Hedley, Jr.','Rick Springfield',NULL,NULL);
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Graduate',1967,'Before opening in 1936, the bridge was blessed by Cardinal Secretary of State Eugenio Pacelli, who later became Pope Pius XII.','Embassy Pictures Corporation','Embassy Pictures Corporation','Mike Nichols','Calder Willingham','Anne Bancroft','Dustin Hoffman','Katharine Ross');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Star Trek IV: The Voyage Home',1986,'Before the 1906 earthquake, the land on which Marina Green sits was a tidal marsh, and rubble from the earthquake was dumped on the site. However, the site was filled in to provide land for the 1915 Panama-Pacific Exhibition.','Paramount Pictures','Paramount Pictures','Leonard Nimoy','Steve Meerson','William Shatner','Leonard Nimoy','George Takei');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Bullitt',1968,'Before the 1906 earthquake, the land on which Marina Green sits was a tidal marsh, and rubble from the earthquake was dumped on the site. However, the site was filled in to provide land for the 1915 Panama-Pacific Exhibition.','Warner Brothers / Seven Arts
Seven Arts','Warner Brothers','Peter Yates','Alan R. Trustman','Steve McQueen','Jacqueline Bisset','Robert Vaughn');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Vertigo',1958,'Built in 1924, the Legion of Honor is a 3/4 replica of the Parisian Palais de la Legion d''Honneur.','Alfred J. Hitchcock Productions','Paramount Pictures','Alfred Hitchcock','Alec Coppel','James Stewart','Kim Novak','Barbara Bel Geddes');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('A Jitney Elopement',1915,'During San Francisco''s Gold Rush era, the Park was part of an area designated as the "Great Sand Waste".','The Essanay Film Manufacturing Company','General Film Company','Charles Chaplin','Charles Chaplin','Charles Chaplin','Edna Purviance',NULL);
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Bullitt',1968,'Before opening in 1936, the bridge was blessed by Cardinal Secretary of State Eugenio Pacelli, who later became Pope Pius XII.','Warner Brothers / Seven Arts
Seven Arts','Warner Brothers','Peter Yates','Alan R. Trustman','Steve McQueen','Jacqueline Bisset','Robert Vaughn');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Shadow of the Thin Man',1941,'Before opening in 1936, the bridge was blessed by Cardinal Secretary of State Eugenio Pacelli, who later became Pope Pius XII.','Metro-Goldwyn Mayer','Metro-Goldwyn Mayer','W.S. Van Dyke','Harry Kurnitz','William Powell','Myrna Loy','Barry Nelson');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Experiment in Terror',1962,'The hotel was destroyed in the 1906 earthquake and fire, had to be rebuilt, and was reopened in 1909.','Columbia Pictures Corporation','Columbia Pictures','Blake Edwards','The Gordons','Glenn Ford','Lee Remick','Stefanie Powers');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Invasion of the Body Snatchers',1978,'The Pyramid was the tallest skyscraper west of the Mississippi from 1972-1974, until it was surpassed by Los Angeles'' Aon Center.','Solofilm','United Artists','Philip Kaufman','Jack Finney','Donald Sutherland','Jeff Goldblum','Brooke Adams');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Dream with the Fishes',1997,'Before opening in 1936, the bridge was blessed by Cardinal Secretary of State Eugenio Pacelli, who later became Pope Pius XII.','3 Ring Circus Films','Sony Pictures Classics','Finn Taylor','Finn Taylor & Jeffrey Brown','David Arquette','Brad Hunt',NULL);
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Freebie and the Bean',1974,'The Steinhart Aquarium is home to over 38,000 animals, which represent more than 900 species.','Warner Bros. Pictures','American Broadcasting Company (ABC)','Richard Rush','Robert Kaufman','Alan Arkin','James Caan','Loretta Swit');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Time After Time',1979,'Before the 1906 earthquake, the land on which Marina Green sits was a tidal marsh, and rubble from the earthquake was dumped on the site. However, the site was filled in to provide land for the 1915 Panama-Pacific Exhibition.','Orion Pictures Corp.','Columbia Broadcasting System (CBS)','Nicholas Meyer','Karl Alexander','Malcolm McDowell','Mary Steenburgen','David Warner');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('D.O.A',1950,'The hotel was originally supposed to be named the Crocker Hotel, after Charles Founder the railroad magnate who founded it. However, the hotel took the name the St. Francis after one of the earliest Gold Rush hotels.','Cardinal Pictures','United Artists','Rudolph Mate','Russell Rouse','Edmond O''Brien','Pamela Britton','Luther Adler');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Herbie Rides Again',1974,'The hotel was destroyed in the 1906 earthquake and fire, had to be rebuilt, and was reopened in 1909.','Walt Disney Productions','Buena Vista Distribution','Robert Stevenson','Bill Walsh','Helen Hayes','Ken Berry','Stefanie Powers');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Junior',1994,'Designed in 1970, the Chinatown Gate (aka the Dragon Gate) is based on ceremonial gates found in Chinese villages.','Northern Lights Entertainment','Universal Pictures','Ivan Reitman','Kevin Wade','Arnold Schwarzenegger','Danny DeVito','Emma Thompson');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Family Plot',1976,'Railroad tycoons like Leland Stanford (founder of Stanford University) lived in Nob Hill at the turn of the 20th Century. The 1906 earthquake completely destroyed Nob Hill, with the exception of the wall that surrounded the mansions of Stanford and his neighbor Mark Hopkins.','Universal Pictures','Universal Pictures','Alfred Hitchcock','Ernest Lehman','Karen Black','Bruce Dern','Barbara Harris');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Conversation',1974,'The hotel was originally supposed to be named the Crocker Hotel, after Charles Founder the railroad magnate who founded it. However, the hotel took the name the St. Francis after one of the earliest Gold Rush hotels.','American Zoetrope','Paramount Pictures','Francis Ford Coppola','Francis Ford Coppola','Gene Hackman','John Cazale','Allen Garfield');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Game',1997,'Before opening in 1936, the bridge was blessed by Cardinal Secretary of State Eugenio Pacelli, who later became Pope Pius XII.','Polygram Filmed Entertainment','Polygram Filmed Entertainment','David Fincher','John Brancato','Michael Douglas','Sean Penn','Deborah Kara Unger');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Freebie and the Bean',1974,'The Pyramid was the tallest skyscraper west of the Mississippi from 1972-1974, until it was surpassed by Los Angeles'' Aon Center.','Warner Bros. Pictures','American Broadcasting Company (ABC)','Richard Rush','Robert Kaufman','Alan Arkin','James Caan','Loretta Swit');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Presidio',1988,'In 1776, Spain made the Presidio a fortified area. The area was then given to Mexico, but then given to the US in 1848. The 1994 demilitarization of the area in 1994 marked the end of its 219 years of military use.','Paramount Pictures','Paramount Pictures','Peter Hyams','Larry Ferguson','Sean Connery','Mark Harmon','Meg Ryan');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Lineup',1958,'The Steinhart Aquarium is home to over 38,000 animals, which represent more than 900 species.','Pajemer Productions','Columbia Pictures','Don Siegel','Stirling Silliphant','Eli Wallach','Robert Keith','Richard Jaeckel');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Dirty Harry',1971,'Before the 1906 earthquake, the land on which Marina Green sits was a tidal marsh, and rubble from the earthquake was dumped on the site. However, the site was filled in to provide land for the 1915 Panama-Pacific Exhibition.','The Malpaso Company','Warner Brothers','Don Siegel','Harry Julian Fink','Clint Eastwood','Harry Guardino',NULL);
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Game',1997,'In 1776, Spain made the Presidio a fortified area. The area was then given to Mexico, but then given to the US in 1848. The 1994 demilitarization of the area in 1994 marked the end of its 219 years of military use.','Polygram Filmed Entertainment','Polygram Filmed Entertainment','David Fincher','John Brancato','Michael Douglas','Sean Penn','Deborah Kara Unger');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Jade',1995,'The hotel was destroyed in the 1906 earthquake and fire, had to be rebuilt, and was reopened in 1909.','Paramount Pictures','Paramount Pictures','William Friedkin','Joe Eszterhas','David Caruso','Linda Fiorentino','Chazz Palminteri');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Patch Adams',1998,'In 1776, Spain made the Presidio a fortified area. The area was then given to Mexico, but then given to the US in 1848. The 1994 demilitarization of the area in 1994 marked the end of its 219 years of military use.','Bungalow 78 Productions','Universal Pictures','Tom Shadyac','Steve Oedekerk','Robin Williams','Philip Seymour Hoffman',NULL);
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Conversation',1974,'During the Civil War, pro-Union rallies were held in the Square, and thus the area was called "Union Square".','American Zoetrope','Paramount Pictures','Francis Ford Coppola','Francis Ford Coppola','Gene Hackman','John Cazale','Allen Garfield');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Woman on the Run',1950,'The Emporium, a department store, stood in this location. Bloomingdale''s is now located here.','Fidelity Pictures Corporation','Universal Pictures','Norman Foster','Norman Foster','Ann Sheridan','Dennis O''Keefe','Robert Keith');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Lady from Shanghai',1947,'The Steinhart Aquarium is home to over 38,000 animals, which represent more than 900 species.','Columbia Pictures Corp.','Columbia Pictures','Orson Welles','Orson Welles','Rita Hayworth','Orson Welles','Everett Sloane');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Conversation',1974,'A partially-above ground parking structure near the building made it necessary for architects to make the Alcoa Building''s diagonal bracing visible, instead of placing it inside and drastically reducing the amount usable interior space.','American Zoetrope','Paramount Pictures','Francis Ford Coppola','Francis Ford Coppola','Gene Hackman','John Cazale','Allen Garfield');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Right Stuff',1983,'Supposedly, the Cow Palace''s name derives from a newspaper editorial in which the writer wonders whether the soon-to-be-built structure for livestock was a "palace for cows".','The Ladd Company','The Ladd Company','Philip Kaufman','Philip Kaufman','Sam Shepard','Scott Glenn','Ed Harris');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Game',1997,'Before opening in 1936, the bridge was blessed by Cardinal Secretary of State Eugenio Pacelli, who later became Pope Pius XII.','Polygram Filmed Entertainment','Polygram Filmed Entertainment','David Fincher','John Brancato','Michael Douglas','Sean Penn','Deborah Kara Unger');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Last Black Man in San Francisco',2019,NULL,'LBMISF, LLC','A36','Joe Talbot','Joe Talbot, Jimmie Fails, Rob Richert','Jimmie Fails','Jonathan Majors','Danny Glover');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Last Black Man in San Francisco',2019,NULL,'LBMISF, LLC','A35','Joe Talbot','Joe Talbot, Jimmie Fails, Rob Richert','Jimmie Fails','Jonathan Majors','Danny Glover');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Star Trek IV: The Voyage Home',1986,'Before the 1906 earthquake, the land on which Marina Green sits was a tidal marsh, and rubble from the earthquake was dumped on the site. However, the site was filled in to provide land for the 1915 Panama-Pacific Exhibition.','Paramount Pictures','Paramount Pictures','Leonard Nimoy','Steve Meerson','William Shatner','Leonard Nimoy','George Takei');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('D.O.A',1950,'During the Civil War, pro-Union rallies were held in the Square, and thus the area was called "Union Square".','Cardinal Pictures','United Artists','Rudolph Mate','Russell Rouse','Edmond O''Brien','Pamela Britton','Luther Adler');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Woman on the Run',1950,'The Emporium, a department store, stood in this location. Bloomingdale''s is now located here.','Fidelity Pictures Corporation','Universal Pictures','Norman Foster','Norman Foster','Ann Sheridan','Dennis O''Keefe','Robert Keith');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Around the Fire',1998,'On Jan. 25, 1878, the King Philip ship crashed in Ocean Beach. Occasionally, the ship''s wreckage may be found on the beach-- most recently it was seen in 2007.','Paradigm Studio','Ardustry Home Entertainment','John Jacobsen','John Comerford','Tara Reid',NULL,NULL);
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Always Be My Maybe',2019,'Keanu Reeves'' penthouse suite scenes were filmed at San Francisco''s Fairmont Hotel.','Isla Productions, LLC','Netflix','Nahnatchka Khan','Michael Golamco, Randall Park, Ali Wong','Ali Wong','Randall Park','Keanu Reeves');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Ant-Man and the Wasp',2018,'VFX Plate Shots, chase scene','PYM Particles Productions II, LLC','Walt Disney Studios Motion Pictures','Peyton Reed','Chris McKenna','Paul Rudd','Evangeline Lilly','Michael Douglas');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Last Black Man in San Francisco',2019,NULL,'LBMISF, LLC','A43','Joe Talbot','Joe Talbot, Jimmie Fails, Rob Richert','Jimmie Fails','Jonathan Majors','Danny Glover');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Last Black Man in San Francisco',2019,NULL,'LBMISF, LLC','A52','Joe Talbot','Joe Talbot, Jimmie Fails, Rob Richert','Jimmie Fails','Jonathan Majors','Danny Glover');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Conversation',1974,'A partially-above ground parking structure near the building made it necessary for architects to make the Alcoa Building''s diagonal bracing visible, instead of placing it inside and drastically reducing the amount usable interior space.','American Zoetrope','Paramount Pictures','Francis Ford Coppola','Francis Ford Coppola','Gene Hackman','John Cazale','Allen Garfield');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Ant-Man and the Wasp',2018,'Location of film headquarters','PYM Particles Productions II, LLC','Walt Disney Studios Motion Pictures','Peyton Reed','Chris McKenna','Paul Rudd','Evangeline Lilly','Michael Douglas');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Presidio',1988,'In 1776, Spain made the Presidio a fortified area. The area was then given to Mexico, but then given to the US in 1848. The 1994 demilitarization of the area in 1994 marked the end of its 219 years of military use.','Paramount Pictures','Paramount Pictures','Peter Hyams','Larry Ferguson','Sean Connery','Mark Harmon','Meg Ryan');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('A Jitney Elopement',1915,'During San Francisco''s Gold Rush era, the Park was part of an area designated as the "Great Sand Waste".','The Essanay Film Manufacturing Company','General Film Company','Charles Chaplin','Charles Chaplin','Charles Chaplin','Edna Purviance',NULL);
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Last Black Man in San Francisco',2019,NULL,'LBMISF, LLC','A24','Joe Talbot','Joe Talbot, Jimmie Fails, Rob Richert','Jimmie Fails','Jonathan Majors','Danny Glover');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Last Black Man in San Francisco',2019,NULL,'LBMISF, LLC','A48','Joe Talbot','Joe Talbot, Jimmie Fails, Rob Richert','Jimmie Fails','Jonathan Majors','Danny Glover');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Last Black Man in San Francisco',2019,NULL,'LBMISF, LLC','A50','Joe Talbot','Joe Talbot, Jimmie Fails, Rob Richert','Jimmie Fails','Jonathan Majors','Danny Glover');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Last Black Man in San Francisco',2019,NULL,'LBMISF, LLC','A38','Joe Talbot','Joe Talbot, Jimmie Fails, Rob Richert','Jimmie Fails','Jonathan Majors','Danny Glover');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Last Black Man in San Francisco',2019,NULL,'LBMISF, LLC','A33','Joe Talbot','Joe Talbot, Jimmie Fails, Rob Richert','Jimmie Fails','Jonathan Majors','Danny Glover');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Bullitt',1968,'Before the 1906 earthquake, the land on which Marina Green sits was a tidal marsh, and rubble from the earthquake was dumped on the site. However, the site was filled in to provide land for the 1915 Panama-Pacific Exhibition.','Warner Brothers / Seven Arts
Seven Arts','Warner Brothers','Peter Yates','Alan R. Trustman','Steve McQueen','Jacqueline Bisset','Robert Vaughn');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Last Black Man in San Francisco',2019,'Bus stop','LBMISF, LLC','A27','Joe Talbot','Joe Talbot, Jimmie Fails, Rob Richert','Jimmie Fails','Jonathan Majors','Danny Glover');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Ant-Man and the Wasp',2018,'Stunt driving scene','PYM Particles Productions II, LLC','Walt Disney Studios Motion Pictures','Peyton Reed','Chris McKenna','Paul Rudd','Evangeline Lilly','Michael Douglas');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Last Black Man in San Francisco',2019,NULL,'LBMISF, LLC','A25','Joe Talbot','Joe Talbot, Jimmie Fails, Rob Richert','Jimmie Fails','Jonathan Majors','Danny Glover');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Last Black Man in San Francisco',2019,NULL,'LBMISF, LLC','A54','Joe Talbot','Joe Talbot, Jimmie Fails, Rob Richert','Jimmie Fails','Jonathan Majors','Danny Glover');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Last Black Man in San Francisco',2019,NULL,'LBMISF, LLC','A46','Joe Talbot','Joe Talbot, Jimmie Fails, Rob Richert','Jimmie Fails','Jonathan Majors','Danny Glover');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Candidate',1972,'The hotel was originally supposed to be named the Crocker Hotel, after Charles Founder the railroad magnate who founded it. However, the hotel took the name the St. Francis after one of the earliest Gold Rush hotels.','Redford-Ritchie Productions','Warner Bros. Pictures','Michael Ritchie','Jeremy Larner','Robert Redford','Peter Boyle',NULL);
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Game',1997,'The hotel was destroyed in the 1906 earthquake and fire, had to be rebuilt, and was reopened in 1909.','Polygram Filmed Entertainment','Polygram Filmed Entertainment','David Fincher','John Brancato','Michael Douglas','Sean Penn','Deborah Kara Unger');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Dream with the Fishes',1997,'Before opening in 1936, the bridge was blessed by Cardinal Secretary of State Eugenio Pacelli, who later became Pope Pius XII.','3 Ring Circus Films','Sony Pictures Classics','Finn Taylor','Finn Taylor & Jeffrey Brown','David Arquette','Brad Hunt',NULL);
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Right Stuff',1983,'Supposedly, the Cow Palace''s name derives from a newspaper editorial in which the writer wonders whether the soon-to-be-built structure for livestock was a "palace for cows".','The Ladd Company','The Ladd Company','Philip Kaufman','Philip Kaufman','Sam Shepard','Scott Glenn','Ed Harris');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Bitter Melon',2018,'The film won Best Narrative Feature at the San Diego Asian Film Festival.','Bitter Melon Film LLC/Mammoth Pictures','ABS-CBN, Gravitas Ventures','H.P. Mendoza','H.P. Mendoza','Jon Norman Schneider','Patrick Epino','Brian Rivera');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Vertigo',1958,'Built in 1924, the Legion of Honor is a 3/4 replica of the Parisian Palais de la Legion d''Honneur.','Alfred J. Hitchcock Productions','Paramount Pictures','Alfred Hitchcock','Alec Coppel','James Stewart','Kim Novak','Barbara Bel Geddes');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Basic Instinct',1992,'The Steinhart Aquarium is home to over 38,000 animals, which represent more than 900 species.','Carolco Pictures','TriStar Pictures','Paul Verhoeven','Joe Eszterhas','Michael Douglas','Sharon Stone','George Dzundza');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Patch Adams',1998,'The hotel was destroyed in the 1906 earthquake and fire, had to be rebuilt, and was reopened in 1909.','Bungalow 78 Productions','Universal Pictures','Tom Shadyac','Steve Oedekerk','Robin Williams','Philip Seymour Hoffman',NULL);
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Last Black Man in San Francisco',2019,NULL,'LBMISF, LLC','A37','Joe Talbot','Joe Talbot, Jimmie Fails, Rob Richert','Jimmie Fails','Jonathan Majors','Danny Glover');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Last Black Man in San Francisco',2019,NULL,'LBMISF, LLC','A45','Joe Talbot','Joe Talbot, Jimmie Fails, Rob Richert','Jimmie Fails','Jonathan Majors','Danny Glover');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Graduate',1967,'Before opening in 1936, the bridge was blessed by Cardinal Secretary of State Eugenio Pacelli, who later became Pope Pius XII.','Embassy Pictures Corporation','Embassy Pictures Corporation','Mike Nichols','Calder Willingham','Anne Bancroft','Dustin Hoffman','Katharine Ross');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Conversation',1974,'The hotel was originally supposed to be named the Crocker Hotel, after Charles Founder the railroad magnate who founded it. However, the hotel took the name the St. Francis after one of the earliest Gold Rush hotels.','American Zoetrope','Paramount Pictures','Francis Ford Coppola','Francis Ford Coppola','Gene Hackman','John Cazale','Allen Garfield');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Junior',1994,'Designed in 1970, the Chinatown Gate (aka the Dragon Gate) is based on ceremonial gates found in Chinese villages.','Northern Lights Entertainment','Universal Pictures','Ivan Reitman','Kevin Wade','Arnold Schwarzenegger','Danny DeVito','Emma Thompson');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Last Black Man in San Francisco',2019,NULL,'LBMISF, LLC','A53','Joe Talbot','Joe Talbot, Jimmie Fails, Rob Richert','Jimmie Fails','Jonathan Majors','Danny Glover');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Last Black Man in San Francisco',2019,NULL,'LBMISF, LLC','A32','Joe Talbot','Joe Talbot, Jimmie Fails, Rob Richert','Jimmie Fails','Jonathan Majors','Danny Glover');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Last Black Man in San Francisco',2019,NULL,'LBMISF, LLC','A55','Joe Talbot','Joe Talbot, Jimmie Fails, Rob Richert','Jimmie Fails','Jonathan Majors','Danny Glover');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Patch Adams',1998,'In 1776, Spain made the Presidio a fortified area. The area was then given to Mexico, but then given to the US in 1848. The 1994 demilitarization of the area in 1994 marked the end of its 219 years of military use.','Bungalow 78 Productions','Universal Pictures','Tom Shadyac','Steve Oedekerk','Robin Williams','Philip Seymour Hoffman',NULL);
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Family Plot',1976,'Railroad tycoons like Leland Stanford (founder of Stanford University) lived in Nob Hill at the turn of the 20th Century. The 1906 earthquake completely destroyed Nob Hill, with the exception of the wall that surrounded the mansions of Stanford and his neighbor Mark Hopkins.','Universal Pictures','Universal Pictures','Alfred Hitchcock','Ernest Lehman','Karen Black','Bruce Dern','Barbara Harris');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Last Black Man in San Francisco',2019,NULL,'LBMISF, LLC','A44','Joe Talbot','Joe Talbot, Jimmie Fails, Rob Richert','Jimmie Fails','Jonathan Majors','Danny Glover');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Herbie Rides Again',1974,'The hotel was destroyed in the 1906 earthquake and fire, had to be rebuilt, and was reopened in 1909.','Walt Disney Productions','Buena Vista Distribution','Robert Stevenson','Bill Walsh','Helen Hayes','Ken Berry','Stefanie Powers');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Last Black Man in San Francisco',2019,'Boat dock','LBMISF, LLC','A26','Joe Talbot','Joe Talbot, Jimmie Fails, Rob Richert','Jimmie Fails','Jonathan Majors','Danny Glover');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('D.O.A',1950,'The hotel was originally supposed to be named the Crocker Hotel, after Charles Founder the railroad magnate who founded it. However, the hotel took the name the St. Francis after one of the earliest Gold Rush hotels.','Cardinal Pictures','United Artists','Rudolph Mate','Russell Rouse','Edmond O''Brien','Pamela Britton','Luther Adler');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Last Black Man in San Francisco',2019,NULL,'LBMISF, LLC','A56','Joe Talbot','Joe Talbot, Jimmie Fails, Rob Richert','Jimmie Fails','Jonathan Majors','Danny Glover');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Last Black Man in San Francisco',2019,NULL,'LBMISF, LLC','A29','Joe Talbot','Joe Talbot, Jimmie Fails, Rob Richert','Jimmie Fails','Jonathan Majors','Danny Glover');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Sense8 - Season 2',2016,'Many films have shot scene in and around the building including Raiders of the Lost Ark, Invasion of the Body Snatchers, Dirty Harry, The Towering Inferno, A View to a Kill and most recently, Milk. The Christmas party scene for this show was shot in the Rotunda.','Unpronounceable Productions, LLC','Netflix','Wachowski Siblings','J. Michael Straczynski, Wachowiski Siblings','Jamie Clayton','Daryl Hannah','Naveen Andrews');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Last Black Man in San Francisco',2019,NULL,'LBMISF, LLC','A40','Joe Talbot','Joe Talbot, Jimmie Fails, Rob Richert','Jimmie Fails','Jonathan Majors','Danny Glover');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Freebie and the Bean',1974,'Railroad tycoons like Leland Stanford (founder of Stanford University) lived in Nob Hill at the turn of the 20th Century. The 1906 earthquake completely destroyed Nob Hill, with the exception of the wall that surrounded the mansions of Stanford and his neighbor Mark Hopkins.','Warner Bros. Pictures','American Broadcasting Company (ABC)','Richard Rush','Robert Kaufman','Alan Arkin','James Caan','Loretta Swit');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Last Black Man in San Francisco',2019,NULL,'LBMISF, LLC','A30','Joe Talbot','Joe Talbot, Jimmie Fails, Rob Richert','Jimmie Fails','Jonathan Majors','Danny Glover');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Dr. Dolittle 2',2001,'In 1776, Spain made the Presidio a fortified area. The area was then given to Mexico, but then given to the US in 1848. The 1994 demilitarization of the area in 1994 marked the end of its 219 years of military use.','Twentieth Century Fox Film Corp.','Twentieth Century Fox Film Corp.','Steve Carr','Larry Levin','Eddie Murphy','Kristen Wilson',NULL);
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Freebie and the Bean',1974,'The Steinhart Aquarium is home to over 38,000 animals, which represent more than 900 species.','Warner Bros. Pictures','American Broadcasting Company (ABC)','Richard Rush','Robert Kaufman','Alan Arkin','James Caan','Loretta Swit');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Game',1997,'In 1776, Spain made the Presidio a fortified area. The area was then given to Mexico, but then given to the US in 1848. The 1994 demilitarization of the area in 1994 marked the end of its 219 years of military use.','Polygram Filmed Entertainment','Polygram Filmed Entertainment','David Fincher','John Brancato','Michael Douglas','Sean Penn','Deborah Kara Unger');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Lineup',1958,'The Steinhart Aquarium is home to over 38,000 animals, which represent more than 900 species.','Pajemer Productions','Columbia Pictures','Don Siegel','Stirling Silliphant','Eli Wallach','Robert Keith','Richard Jaeckel');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Always Be My Maybe',2019,'When Sasha, Keanu, Jenny and Marcus go for dinner together, the restaurant (known in the film as "maximal") is actually San Francisco''s Contemporary Jewish Museum.','Isla Productions, LLC','Netflix','Nahnatchka Khan','Michael Golamco, Randall Park, Ali Wong','Ali Wong','Randall Park','Keanu Reeves');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('GirlBoss',2017,'The restaurant was given the honor of "America''s Best Burrito" in 2014 by ESPN''s FiveThirtyEight.','Hippolyta Productions, LLC','Netflix','Jamie Babbit, Amanda Brotchie, Steven K. Tsuchida, Christian Ditter, John Riggi','Kay Cannon','Britt Robertson','Ellie Reed','Amanda Rea');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Last Black Man in San Francisco',2019,NULL,'LBMISF, LLC','A39','Joe Talbot','Joe Talbot, Jimmie Fails, Rob Richert','Jimmie Fails','Jonathan Majors','Danny Glover');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Lady from Shanghai',1947,'The Steinhart Aquarium is home to over 38,000 animals, which represent more than 900 species.','Columbia Pictures Corp.','Columbia Pictures','Orson Welles','Orson Welles','Rita Hayworth','Orson Welles','Everett Sloane');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Bachelor',1999,'The Steinhart Aquarium is home to over 38,000 animals, which represent more than 900 species.','George Street Pictures','New Line Cinema','Gary Sinyor','Steve Cohen','Chris O''Donnell','Renee Zellweger',NULL);
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Last Black Man in San Francisco',2019,NULL,'LBMISF, LLC','A41','Joe Talbot','Joe Talbot, Jimmie Fails, Rob Richert','Jimmie Fails','Jonathan Majors','Danny Glover');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Last Black Man in San Francisco',2019,NULL,'LBMISF, LLC','A31','Joe Talbot','Joe Talbot, Jimmie Fails, Rob Richert','Jimmie Fails','Jonathan Majors','Danny Glover');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Dirty Harry',1971,'Before the 1906 earthquake, the land on which Marina Green sits was a tidal marsh, and rubble from the earthquake was dumped on the site. However, the site was filled in to provide land for the 1915 Panama-Pacific Exhibition.','The Malpaso Company','Warner Brothers','Don Siegel','Harry Julian Fink','Clint Eastwood','Harry Guardino',NULL);
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Ant-Man and the Wasp',2018,'Stunt scene involving car jump','PYM Particles Productions II, LLC','Walt Disney Studios Motion Pictures','Peyton Reed','Chris McKenna','Paul Rudd','Evangeline Lilly','Michael Douglas');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Pushing Dead',2016,'Pushing Dead won the Audience Award for  Frameline San Francisco International LGBTQ Film Festival 
2016','Pushing Dead , LLC','TBD','Tom Brown','Tom Brown','Danny Glover','James Roday','Robin Weigert');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Last Black Man in San Francisco',2019,NULL,'LBMISF, LLC','A51','Joe Talbot','Joe Talbot, Jimmie Fails, Rob Richert','Jimmie Fails','Jonathan Majors','Danny Glover');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Invasion of the Body Snatchers',1978,'The Pyramid was the tallest skyscraper west of the Mississippi from 1972-1974, until it was surpassed by Los Angeles'' Aon Center.','Solofilm','United Artists','Philip Kaufman','Jack Finney','Donald Sutherland','Jeff Goldblum','Brooke Adams');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Last Black Man in San Francisco',2019,NULL,'LBMISF, LLC','A34','Joe Talbot','Joe Talbot, Jimmie Fails, Rob Richert','Jimmie Fails','Jonathan Majors','Danny Glover');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('High Crimes',2002,'During the Civil War, pro-Union rallies were held in the Square, and thus the area was called "Union Square".','Twentieth Century Fox Film Corporation','Twentieth Century Fox Film Corporation','Mel Brooks','Mel Brooks','Mel Brooks','Madeline Kahn',NULL);
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('George of the Jungle',1997,'Before opening in 1936, the bridge was blessed by Cardinal Secretary of State Eugenio Pacelli, who later became Pope Pius XII.','Walt Disney Pictures','Buena Vista Pictures','Sam Weisman','Jay Ward','Brendan Fraser','Leslie Mann',NULL);
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Jade',1995,'The hotel was destroyed in the 1906 earthquake and fire, had to be rebuilt, and was reopened in 1909.','Paramount Pictures','Paramount Pictures','William Friedkin','Joe Eszterhas','David Caruso','Linda Fiorentino','Chazz Palminteri');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Last Black Man in San Francisco',2019,'Grandpa Allen''s home','LBMISF, LLC','A28','Joe Talbot','Joe Talbot, Jimmie Fails, Rob Richert','Jimmie Fails','Jonathan Majors','Danny Glover');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Final Analysis',1992,'The hotel was originally supposed to be named the Crocker Hotel, after Charles Founder the railroad magnate who founded it. However, the hotel took the name the St. Francis after one of the earliest Gold Rush hotels.','Warner Bros. Pictures','Warner Bros. Pictures','Phil Joanou','Robert Berger','Richard Gere','Kim Basinger',NULL);
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Ant-Man and the Wasp',2018,'Car stunt scene','PYM Particles Productions II, LLC','Walt Disney Studios Motion Pictures','Peyton Reed','Chris McKenna','Paul Rudd','Evangeline Lilly','Michael Douglas');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Shadow of the Thin Man',1941,'Before opening in 1936, the bridge was blessed by Cardinal Secretary of State Eugenio Pacelli, who later became Pope Pius XII.','Metro-Goldwyn Mayer','Metro-Goldwyn Mayer','W.S. Van Dyke','Harry Kurnitz','William Powell','Myrna Loy','Barry Nelson');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Experiment in Terror',1962,'The hotel was destroyed in the 1906 earthquake and fire, had to be rebuilt, and was reopened in 1909.','Columbia Pictures Corporation','Columbia Pictures','Blake Edwards','The Gordons','Glenn Ford','Lee Remick','Stefanie Powers');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Bullitt',1968,'Before opening in 1936, the bridge was blessed by Cardinal Secretary of State Eugenio Pacelli, who later became Pope Pius XII.','Warner Brothers / Seven Arts
Seven Arts','Warner Brothers','Peter Yates','Alan R. Trustman','Steve McQueen','Jacqueline Bisset','Robert Vaughn');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Bedazzled',2000,'Installed in 1975, the Vaillancourt Fountain is officially titled, "Québec Libre!". The night before the sculpture''s inauguration, artist Armand Vaillancourt inscribed "Québec libre!" in red letters on the sculpture. The next day when he noticed that the note had been erased, Vaillancourt jumped on the statue to re-inscribe his message.','Twentieth Century Fox Film Corp.','Twentieth Century Fox Film Corp.','Harold Ramis','Harold Ramis','Brendan Fraser','Elizabeth Hurley',NULL);
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Last Black Man in San Francisco',2019,NULL,'LBMISF, LLC','A42','Joe Talbot','Joe Talbot, Jimmie Fails, Rob Richert','Jimmie Fails','Jonathan Majors','Danny Glover');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('When a Man Loves a Woman',1994,'The hotel was originally supposed to be named the Crocker Hotel, after Charles Founder the railroad magnate who founded it. However, the hotel took the name the St. Francis after one of the earliest Gold Rush hotels.','Touchstone Pictures','Buena Vista Pictures','Luis Mandoki','Ronald Bass','Andy Garcia','Meg Ryan',NULL);
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Hard to Hold',1984,'In 1945 the Fairmont hosted the United Nations Conference on International Organization as delegates arrived to draft a charter for the organization. The U.S. Secretary of State, Edward Stettinius drafted the charter in the hotel''s Garden Room.','Universal Pictures','Universal Pictures','Larry Peerce','Thomas Hedley, Jr.','Rick Springfield',NULL,NULL);
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Venom',2018,'Motorcycle stunt scene','L.O.Z. Productions, Inc.','Columbia Pictures, Sony Pictures Releasing','Ruben Fleischer','Jeff Pinkner, Scott Rosenberg','Tom Hardy','Michelle Wiliams','Riz Ahmed');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Last Black Man in San Francisco',2019,NULL,'LBMISF, LLC','A49','Joe Talbot','Joe Talbot, Jimmie Fails, Rob Richert','Jimmie Fails','Jonathan Majors','Danny Glover');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Freebie and the Bean',1974,'The Pyramid was the tallest skyscraper west of the Mississippi from 1972-1974, until it was surpassed by Los Angeles'' Aon Center.','Warner Bros. Pictures','American Broadcasting Company (ABC)','Richard Rush','Robert Kaufman','Alan Arkin','James Caan','Loretta Swit');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Last Black Man in San Francisco',2019,NULL,'LBMISF, LLC','A47','Joe Talbot','Joe Talbot, Jimmie Fails, Rob Richert','Jimmie Fails','Jonathan Majors','Danny Glover');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('The Conversation',1974,'During the Civil War, pro-Union rallies were held in the Square, and thus the area was called "Union Square".','American Zoetrope','Paramount Pictures','Francis Ford Coppola','Francis Ford Coppola','Gene Hackman','John Cazale','Allen Garfield');
INSERT INTO movie(Title,Release_Year,Fun_Facts,Production_Company,Distributor,Director,Writer,Actor_1,Actor_2,Actor_3) VALUES ('Time After Time',1979,'Before the 1906 earthquake, the land on which Marina Green sits was a tidal marsh, and rubble from the earthquake was dumped on the site. However, the site was filled in to provide land for the 1915 Panama-Pacific Exhibition.','Orion Pictures Corp.','Columbia Broadcasting System (CBS)','Nicholas Meyer','Karl Alexander','Malcolm McDowell','Mary Steenburgen','David Warner');
